//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.19 at 12:40:25 AM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.uidai.gov.in/authentication/uid-auth-response/1.0")
package in.gov.uidai.authentication.uid_auth_response._1;
